version: '3.7'

services:
  spark:
    image: apache/spark:v3.3.2
    container_name: spark
    ports:
      - "8080:8080"
      - "7077:7077"
  postgres:
    image: postgres:15.2
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medical_data
    ports:
      - "5432:5432"