version: '3.4'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zookeeper
    environment:
      SERVICE_NAME: zookeeper
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9093,INTERNAL://localhost:9092"
      KAFKA_LISTENERS: "PLAINTEXT://:9093,INTERNAL://:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_SEGMENT_MS: 300000
      KAFKA_LOG_SEGMENT_BYTES: 10485760
      KAFKA_PRODUCER_MAX_REQUEST_SIZE: 2147483648 # 2GB
      KAFKA_CONSUMER_MAX_PARTITION_FETCH_BYTES: 2147483648   
      KAFKA_AUTO_CREATE_TOPICS: 1  
      KAFKA_NUM_PARTITIONS: 5
      KAFKA_MESSAGE_MAX_BYTES: 1000000000
    ports:
      - "9092:9092"
      - "9101:9101"

  kafka-ui:
    image: provectuslabs/kafka-ui:master
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9093